### ISSUE TITLE
您的 guide 整理得很棒！

### ISSUE THREAD

**Issue by amowu** [macdao/ocds-guide-to-setting-up-mac#10]
在這裡毛遂自薦一下自己的項目 https://github.com/amowu/dotfiles
這份腳本可以自動執行以下動作：
1. 透過 Homebrew 安裝 packages
2. 透過 Homebrew Cask 安裝 font
3. 透過 Homebrew Cask 安裝 app
4. 連結自己的 .files (ex: .zshrc, .gitconfig, .vimrc, ...)
5. 設定 OS X 的 settings (ex: 全键盘控制, ...)
6. 從 Dropbox 回復一些應用的設定 (ex: Sublime Text setting, plugin, SSH keys, ...)
歡迎參考＆一起交流 :-)

**Comment by macdao** [comment]
谢谢夸奖！
你的dotfiles项目看上去很酷，我用一下～

**Comment by Chadwickwicky** [comment]
Could u please put that in english??
