### ISSUE TITLE
转载咨询

### ISSUE THREAD

**Issue by huanglimin** [macdao/ocds-guide-to-setting-up-mac#11]
Hi，macdao

我是伯乐在线的小编。请问可以把您的这篇文章转到伯乐在线网站和微信么？

我们会在显著之处标注【来源】和【链接】，类似文章开头：http://blog.jobbole.com/88729/ （您可以打开看看）

不知您的新浪微博是多少？如果有，我们会@ 您。

期待回复。谢谢。

**Comment by macdao** [comment]
好啊，欢迎转载。我的weibo是`祁兮`

**Comment by Chadwickwicky** [comment]
Could u please send this in english??

**Comment by macdao** [comment]
@Chadwickwicky good idea, it's in the plan :)

**Comment by macdao** [comment]
@Chadwickwicky thanks https://github.com/fff who contributed an english version: https://github.com/macdao/ocds-guide-to-setting-up-mac/blob/master/README.en.md

**Comment by xirong** [comment]
OK ，转载到我的公众号了 [搭配更高效的 Mac 工作环境](http://mp.weixin.qq.com/s?__biz=MzIzNzEzNDMxOA==&mid=402346585&idx=1&sn=38eb3d68846118e827bcb9366430871b#rd)，已经表明作者您的版权和出处了。微信公众号的排版太费劲了，花费不少时间把这篇文章排出来，效果比 github 差远了还，

**Comment by macdao** [comment]
@xirong 好的。谢谢～
