### ISSUE TITLE
rbenv 就是这样一个轻量级工具

### ISSUE THREAD

**Issue by freewind** [macdao/ocds-guide-to-setting-up-mac#3]
很多像这样的词，比如`rbenv`，我个人习惯觉得用“行内代码”表示特定名字。不过你也可能有不同习惯

**Comment by macdao** [comment]
现在我的想法是，如果是表示一个特定的引用，比如命令、菜单上的文字、某个工具在brew中的ID，则使用行内代码。而像rbenv是一个名字，不需要行内代码。

欢迎讨论
