### ISSUE TITLE
关于java版本那块，我一般用jenv，不知道你用过吗？简单使用还不错

### ISSUE THREAD

**Issue by freewind** [macdao/ocds-guide-to-setting-up-mac#4]

**Comment by macdao** [comment]
jenv，发现有几个问题：
- 需要手动把`eval "$(jenv init -)”`加入profile，没有oh my zsh插件
- 需要手动添加JDK，不会自动采集系统JDK
- 需要rehash

**Comment by macdao** [comment]
已经添加了jenv的内容 ec5f94e
