### ISSUE TITLE
scroll reverse这个可以在mac设置里设置的

### ISSUE THREAD

**Issue by morefreeze** [macdao/ocds-guide-to-setting-up-mac#5]
没下这个东西，看描述是不是和配置里的Trackpad->Scroll & Zoom->Scroll direction一样的功能，只要把勾去掉就是双指下划向下滚动了

**Comment by macdao** [comment]
Mac里的设置，会同时更改触摸板和鼠标的方向。我期望的是更改鼠标方向，但保持触摸板方向不变。

可能我写的不够明白，我再斟酌下文字。

**Comment by macdao** [comment]
修改了描述，你看看这样是不是说清楚了？ e0978ec

**Comment by morefreeze** [comment]
没有问题 说清楚了
可以再举个非scroll的例子，比如缩放地图？
反正我是觉得改完后，整个方向都改变后我更习惯，只是个人习惯，推荐这个app我没有意见

**Comment by DonaldDai** [comment]
为什么在用户当前目录下找不到.oh-my-zsh(搜索隐形文件也不行)但是用command＋shift＋G却可以进到文件夹里，这个文件夹是什么属性？

**Comment by macdao** [comment]
@DonaldDai `~/.oh-my-zsh`只是一个普通文件夹，只是用`.`开头，所以被当做隐藏文件夹。我猜测可能你用的方法无法搜索到隐藏文件夹。你可以在终端中用`l ~`看到这个文件夹。

**Comment by DonaldDai** [comment]
hi～我不太会用mac的终端，以前也没有用过unix所以看了你的建议之后我上网上找了教程，学了一遍，用你说的方法看到了.oh-my-zsh的隐藏文件。但是又发现了一个新问题，我在Users／用户／目录下用ls查看，只有Applications文件夹没有applications，但是我用命令行进入applications却成功了，如图（附件）－－－学校生活比较忙，不好意思，回的比较晚。

Date: Sun, 25 Oct 2015 18:59:17 -0700

**Comment by macdao** [comment]
@DonaldDai 默认的Mac文件系统不区分大小写的，所以applications就是Applications文件夹。
你的附件我看不见，不过应该不影响我的判断。

**Comment by DonaldDai** [comment]
好的，3q

Date: Thu, 19 Nov 2015 07:10:28 -0800

**Comment by DonaldDai** [comment]
@macdao 新人刚来，再问一下，用命令行设置git标签的时候提示$ command not found是什么情况？

**Comment by macdao** [comment]
@DonaldDai 能把你的命令放上来看看嘛？

**Comment by DonaldDai** [comment]
@macdao $ git config --global user.name "YOUR NAME"
下面是终端给我的回复
zsh: command not found: $

**Comment by macdao** [comment]
@DonaldDai 试试这个

```
git config --global user.name "YOUR NAME"
```

**Comment by morefreeze** [comment]
抱歉打扰，如果这是个新问题 麻烦还是开新issue提问吧，也便于以后的查找，现在有点歪楼了

**Comment by DonaldDai** [comment]
@morefreeze 好的
